<a href="https://colab.research.google.com/github/ONowakowski/howToDataInPython/blob/master/numpy_how_to.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# Array

1D Array

In [ ]:
a = np.array([0,3]) #jednowymiarowa tablica
print(a)
a

[0 3]


array([0, 3])

In [ ]:
a.shape #ksztalt tablicy

(2,)

In [ ]:
a.size #wymiar tablicy

2

In [ ]:
a.dtype #typ danych

dtype('int64')

2D Array

In [ ]:
a = np.array([[3.2, 4, 6.8], [7.2, 2.1, 4.4]])
print(a, '\n \n')
a

[[3.2 4.  6.8]
 [7.2 2.1 4.4]] 
 



array([[3.2, 4. , 6.8],
       [7.2, 2.1, 4.4]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

3D Array


In [ ]:
a = np.array(
    [[[4, 1, 5],
      [2, 4, 1],
      [9, 12, 0]],
     
     [[2, 1, 5],
      [6, 2, 1],
      [4, 2, 0]]]
)
print(a, '\n\n')
a

[[[ 4  1  5]
  [ 2  4  1]
  [ 9 12  0]]

 [[ 2  1  5]
  [ 6  2  1]
  [ 4  2  0]]] 




array([[[ 4,  1,  5],
        [ 2,  4,  1],
        [ 9, 12,  0]],

       [[ 2,  1,  5],
        [ 6,  2,  1],
        [ 4,  2,  0]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape 
#shape opisuje ilosc tablic od zewnatrz, tzn. w glownym wymiarze sa dwie tablice, 
#kazda z nich ma po 3 tablice (3 wiersze), a kazdy z tych wierszy ma po 3 pozycje 

(2, 3, 3)

# Typy danych

In [ ]:
#za pomoca parametru dtype mozemy okreslic typ danych w tablicy
a = np.array([2.0, 3.1, 2], dtype='int')
a

array([2, 3, 2])

In [ ]:
a = np.array([2.0, 3.1, 2], dtype='complex')
a

array([2. +0.j, 3.1+0.j, 2. +0.j])

In [ ]:
a = np.array([True, False, False])
a.dtype

dtype('bool')

In [ ]:
#ograniczanie typu, np do uzywania kolorow 
#1 sposob 8bit: 
a = np.array([230, 254, 12], dtype=np.int8)
print(a) #(jest ze znakiem wiec tylko do 128, czyli odpada)
a.dtype

[-26  -2  12]


dtype('int8')

In [ ]:
#2 sposob 8bit za pomoca unsigned int 8 
a = np.array([210, 42, 1], dtype=np.uint8)
print(a) #tutaj nie ma znaku, zatem max to 255
a.dtype

[210  42   1]


dtype('uint8')

# Tworzenie tablic

In [ ]:
#tworzenie tablicy wypełnionej zerami o danym ksztalcie
np.zeros(shape=(2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#tworzenie tablicy wypełnionej jedynkami o danym ksztalcie
np.ones(shape=(2,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#tablica wypelniona jakakolwiek wartoscia
np.full(shape=(3,2), fill_value=4, dtype='int')

array([[4, 4],
       [4, 4],
       [4, 4]])

In [ ]:
#ostatnia liczba jest wylaczona!
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#step ustala jakimi liczbami przeskakiwac (np. co dziesiata liczba)
np.arange(start=0, stop=30, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
#malejaco
np.arange(start=100, stop=90, step=-2) #nadal wylaczamy stop

array([100,  98,  96,  94,  92])

In [ ]:
#zmiennoprzecinkowo
np.arange(start=1, stop=2, step=0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
#funkcja linspace wypisuje num elementów równo rozłożonych z podanego przedziału
np.linspace(start=1, stop=2, num=21) #czyli to samo co arange ze step 0.05 ALE włącznie ze stopem

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ])

In [ ]:
#zmiana ksztaltu tablicy
a = np.arange(16)
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
#bez znajomosci ilosci elementow
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])