<a href="https://colab.research.google.com/github/ONowakowski/howToDataInPython/blob/master/numpy_how_to.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


# Array

1D Array

In [ ]:
a = np.array([0,3]) #jednowymiarowa tablica
print(a)
a

[0 3]


array([0, 3])

In [ ]:
a.shape #ksztalt tablicy

(2,)

In [ ]:
a.size #wymiar tablicy

2

In [ ]:
a.dtype #typ danych

dtype('int64')

2D Array

In [ ]:
a = np.array([[3.2, 4, 6.8], [7.2, 2.1, 4.4]])
print(a, '\n \n')
a

[[3.2 4.  6.8]
 [7.2 2.1 4.4]] 
 



array([[3.2, 4. , 6.8],
       [7.2, 2.1, 4.4]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

3D Array


In [ ]:
a = np.array(
    [[[4, 1, 5],
      [2, 4, 1],
      [9, 12, 0]],
     
     [[2, 1, 5],
      [6, 2, 1],
      [4, 2, 0]]]
)
print(a, '\n\n')
a

[[[ 4  1  5]
  [ 2  4  1]
  [ 9 12  0]]

 [[ 2  1  5]
  [ 6  2  1]
  [ 4  2  0]]] 




array([[[ 4,  1,  5],
        [ 2,  4,  1],
        [ 9, 12,  0]],

       [[ 2,  1,  5],
        [ 6,  2,  1],
        [ 4,  2,  0]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape 
#shape opisuje ilosc tablic od zewnatrz, tzn. w glownym wymiarze sa dwie tablice, 
#kazda z nich ma po 3 tablice (3 wiersze), a kazdy z tych wierszy ma po 3 pozycje 

(2, 3, 3)

# Typy danych

In [ ]:
#za pomoca parametru dtype mozemy okreslic typ danych w tablicy
a = np.array([2.0, 3.1, 2], dtype='int')
a

array([2, 3, 2])

In [ ]:
a = np.array([2.0, 3.1, 2], dtype='complex')
a

array([2. +0.j, 3.1+0.j, 2. +0.j])

In [ ]:
a = np.array([True, False, False])
a.dtype

dtype('bool')

In [ ]:
#ograniczanie typu, np do uzywania kolorow 
#1 sposob 8bit: 
a = np.array([230, 254, 12], dtype=np.int8)
print(a) #(jest ze znakiem wiec tylko do 128, czyli odpada)
a.dtype

[-26  -2  12]


dtype('int8')

In [ ]:
#2 sposob 8bit za pomoca unsigned int 8 
a = np.array([210, 42, 1], dtype=np.uint8)
print(a) #tutaj nie ma znaku, zatem max to 255
a.dtype

[210  42   1]


dtype('uint8')

# Tworzenie tablic

In [ ]:
#tworzenie tablicy wypełnionej zerami o danym ksztalcie
np.zeros(shape=(2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#tworzenie tablicy wypełnionej jedynkami o danym ksztalcie
np.ones(shape=(2,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#tablica wypelniona jakakolwiek wartoscia
np.full(shape=(3,2), fill_value=4, dtype='int')

array([[4, 4],
       [4, 4],
       [4, 4]])

In [ ]:
#ostatnia liczba jest wylaczona!
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#step ustala jakimi liczbami przeskakiwac (np. co dziesiata liczba)
np.arange(start=0, stop=30, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
#malejaco
np.arange(start=100, stop=90, step=-2) #nadal wylaczamy stop

array([100,  98,  96,  94,  92])

In [ ]:
#zmiennoprzecinkowo
np.arange(start=1, stop=2, step=0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
#funkcja linspace wypisuje num elementów równo rozłożonych z podanego przedziału
np.linspace(start=1, stop=2, num=21) #czyli to samo co arange ze step 0.05 ALE włącznie ze stopem

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ])

In [ ]:
#zmiana ksztaltu tablicy
a = np.arange(16)
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
#bez znajomosci ilosci elementow
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

#Operacje na tablicach

In [ ]:
a = np.array([3,5,12,0])
b = np.array([5,1,-4, 5])
print(a)
print(b)

[ 3  5 12  0]
[ 5  1 -4  5]


In [ ]:
#konkretne elementy sa poddawane ze soba dzialaniom, tablice musza miec taka sama ilosc elementow
print('a+b = ', a+b)
print('a-b = ',a-b)
print('a*b = ',a*b)
print('a/b = ',a/b) #ta przez ktora dzielimy nie moze zawierac zera!
print('a+3 = ',a+3) #dodanie stalej do kazdej z liczb w tablicy
print('a+2*b = ',a + 2*b)

a+b =  [8 6 8 5]
a-b =  [-2  4 16 -5]
a*b =  [ 15   5 -48   0]
a/b =  [ 0.6  5.  -3.   0. ]
a+3 =  [ 6  8 15  3]
a+2*b =  [13  7  4 10]


In [ ]:
#funkcje do robienia powyzszych
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))

[8 6 8 5]
[-2  4 16 -5]
[ 0.6  5.  -3.   0. ]
[ 15   5 -48   0]


Mnożenie macierzowe

In [ ]:
x = np.array([[2, 5], [1, 4]])
y = np.array([[4, 3], [2, 1]])
print(x, '\n')
print(y)

[[2 5]
 [1 4]] 

[[4 3]
 [2 1]]


In [ ]:
np.dot(x,y)

array([[18, 11],
       [12,  7]])

In [ ]:
x.dot(y)

array([[18, 11],
       [12,  7]])

In [ ]:
x @ y

array([[18, 11],
       [12,  7]])

#Generowanie liczb pseudolosowych

In [4]:
np.random.seed(0) #ustawianie ziarna, by za każdym razem z tym ziarnem losowa liczba była taka sama

In [5]:
np.random.randn() #losowa liczba z rozkladu normalnego, srednia 0, odchylenie 1

1.764052345967664

In [27]:
np.random.rand() #losowa liczba z przedziału 0-1 czyli rozkład jednostajny

0.9689617652602737

In [7]:
np.random.randn(10) #10 losowych wyników z rozkładu normalnego

array([ 0.40015721, -2.2683282 ,  1.33354538, -0.84272405,  1.96992445,
        1.26611853, -0.50587654,  2.54520078,  1.08081191,  0.48431215])

In [10]:
np.random.randn(10,4) #np. 10 próbek po 4 kolumny z rozkładu normalnego

array([[-0.4794198 ,  0.3113635 , -0.77602047, -0.30736481],
       [-0.36652394,  1.11971196, -0.45792242,  0.4253934 ],
       [-0.02797118,  1.47598983,  0.6467801 , -0.36433431],
       [-0.67877739, -0.35362786, -0.74074747, -0.67502183],
       [-0.13278426,  0.61980106,  1.79116846,  0.17100044],
       [-1.72567135,  0.16065854, -0.85898532, -0.20642094],
       [ 0.48842647, -0.83833097,  0.38116374, -0.99090328],
       [ 1.01788005,  0.3415874 , -1.25088622,  0.92525075],
       [-0.90478616,  1.84369153,  1.52550724, -1.44553558],
       [ 0.37716061, -0.07055723,  0.60415971,  0.472149  ]])

In [11]:
np.random.randint(10) #zwraca nieujemną liczbę mniejsza niż argument

6

In [13]:
np.random.randint(low=50, high = 101, size=10) #czyli 10 losowych liczb całkowitych od 50 do 100

array([95, 61, 66, 74, 79, 71, 96, 75, 66, 69])

In [15]:
np.random.choice([4,2,6,2,6,2,1,10,32,22]) #zwraca losowy element z podanej listy (jakiegokolwiek typu)

32

Mieszanie danych

In [16]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.random.shuffle(data) #mieszamy dane w liscie, zmiany zachodza na obiekcie
data

array([0, 2, 5, 9, 6, 1, 8, 3, 7, 4])

#Podstawowe funkcje w NumPy

In [19]:
np.exp(1) #liczba eulera do potegi podanej w nawiasie

2.718281828459045

In [20]:
np.exp(2) 

7.38905609893065

In [21]:
np.sqrt(16) #zwraca pierwiastek w typie float

4.0

In [23]:
np.all([2, 12, 9, 0]) #jesli ktorakolwiek z wartosci w liscie lub tablicy zwraca False to funkcja zwraca False, w innym przypadku True 

False

In [24]:
np.all([2, 23, 44])

True

In [25]:
np.any([0.0, 1, 0]) #jesli ktorakolwiek z wartosci bedzie inna niz False (0) to zwraca true

True

In [26]:
np.any([0, 0.0])

False

In [28]:
a = np.random.rand(5)
print(a)

np.argmax(a) #funkcja argmax zwraca indeks największej wartości w liście

[0.32099724 0.22126269 0.1412639  0.09725993 0.98404224]


4

In [30]:
a[np.argmax(a)] #zdobycie powyższej wartości max

0.9840422413641464

In [33]:
a[np.argmin(a)] #najmniejsza wartość

0.09725992706317388

In [34]:
np.argsort(a) #pokazuje jak trzeba ułożyć indeksy by wartości były posortowane

array([3, 2, 1, 0, 4])

In [35]:
np.max(a)

0.9840422413641464

In [36]:
np.min(a)

0.09725992706317388

In [37]:
np.mean(a) #zwraca średnią

0.3529651999820994

In [38]:
np.median(a) #zwraca mediane

0.22126268518378278

In [39]:
np.std(a) #zwraca odchylenie standardowe

0.3246007886214498

#Indeksowanie, wycinanie

In [40]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
a[2] #konkretny element

2

In [42]:
a[2:6] #elementy od 2 do 6 wylaczajac ostatni

array([2, 3, 4, 5])

In [43]:
a[:10] #elementy od poczatku do 9 elementu

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a[17:] #od 17 el. do konca

array([17, 18, 19])

In [46]:
a[3:-1] #podajac -1 mamy na mysli ostatnia pozycje w zbiorze, w tym przypadku 19, ktora nie zostanie wzieta pod uwage

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [50]:
a[-1:] #zwraca ostatni element

array([19])

In [52]:
a[[13, 19]] #wybiera elementy o indeksach przekazanych w liscie

array([13, 19])

In [55]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
a[2] #wycinamy trzeci wiersz

array([10, 11, 12, 13, 14])

In [59]:
a[:, 0] #wycinamy wszystkie wiersze, pierwsza kolumne

array([ 0,  5, 10, 15])

In [60]:
a[:, -1] #pobieramy ostatnią kolumnę

array([ 4,  9, 14, 19])

In [61]:
a[1, 3] #wyciecie 8, czyli drugi wiersz, czwarta kolumna

8

In [62]:
a[2, 1:4] #wyciecie [11,12,13], czyli trzeci wiersz i kolumny 2-4

array([11, 12, 13])

In [64]:
a[0:2, 1:4] 

array([[1, 2, 3],
       [6, 7, 8]])

In [66]:
b = np.array([np.arange(2), np.arange(4,6), np.arange(11, 13), np.arange(19, 21)])
b

array([[ 0,  1],
       [ 4,  5],
       [11, 12],
       [19, 20]])

In [67]:
a[:, 0:2] = b #przypisywanie wartosci z b pierwszym dwóm kolumnom z tablicy a
a

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  7,  8,  9],
       [11, 12, 12, 13, 14],
       [19, 20, 17, 18, 19]])

#Iterowanie po tablicach

In [68]:
a

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  7,  8,  9],
       [11, 12, 12, 13, 14],
       [19, 20, 17, 18, 19]])

In [69]:
#iterowanie po wierszach
for row in a:
  print(row)

[0 1 2 3 4]
[4 5 7 8 9]
[11 12 12 13 14]
[19 20 17 18 19]


In [72]:
#iterowanie po ntej kolumnie
for row in a:
  print(row[2])

2
7
12
17


In [73]:
#iterowanie po calej tablicy za pomoca wyplaszczenia jej
for item in a.flat:
  print(item)

0
1
2
3
4
4
5
7
8
9
11
12
12
13
14
19
20
17
18
19


#Zmiana rozmiaru tablic

In [74]:
a

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  7,  8,  9],
       [11, 12, 12, 13, 14],
       [19, 20, 17, 18, 19]])

In [75]:
a.shape

(4, 5)

In [76]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  4,  5,  7],
       [ 8,  9, 11, 12],
       [12, 13, 14, 19],
       [20, 17, 18, 19]])

In [79]:
a.ravel() #wyplaszczanie tablicy

array([ 0,  1,  2,  3,  4,  4,  5,  7,  8,  9, 11, 12, 12, 13, 14, 19, 20,
       17, 18, 19])

In [80]:
a.T #transponowanie macierzy, czyli zamiana kolumn na wiersze

array([[ 0,  4, 11, 19],
       [ 1,  5, 12, 20],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

#Maski logiczne

In [85]:
a = np.arange(start=-10, stop=10, step=0.5)
a = a.reshape(10, -1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [86]:
a > 0 #jesli wartosc jest wieksza od zera to True, jesli mniejsza to False

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [87]:
#przekazywanie takiej maski spowoduje uzyskanie jedynie elementow spelniajacych warunek
a[a>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [90]:
b = np.bitwise_and(a > -5, a < 5) #funkcja pomagajaca robic warunek AND

In [91]:
#wstawianie powyzszej maski
a[b]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [92]:
b = np.bitwise_or(a > 5, a < -5)
a[b]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])